# Generated by Django 4.1.4 on 2023-01-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
