# Generated by Django 3.2.10 on 2023-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addr1',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
