# Generated by Django 3.2.10 on 2023-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytable',
            name='save_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
