# Generated by Django 3.2.10 on 2023-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_replytable_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytable',
            name='save_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
